name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: setup Yandex CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          source $HOME/.bashrc

      - name: Restore Service Account Key
        run: |
          echo "${{ secrets.YC_SA_KEY_JSON }}" > key.json

      - name: Configure Yandex CLI
        run: |
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }} 
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc config set compute-default-zone ${{ secrets.YC_ZONE }}
          yc config set registry-id ${{ secrets.YC_REGISTRY_ID }}

      - name: Log in to Container Registry
        run: yc container registry login

      - name: Build Docker image
        run: |
          IMAGE=cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_REGISTRY_ID }}/my-app:${{ github.sha }}
          docker build -t $IMAGE ./app
          echo "Image tagged as $IMAGE"

      - name: Push Docker image
        run: |
          docker push $IMAGE
