#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - "${ssh_key}"

package_update: true
packages:
  - docker.io
  - docker-compose-plugin
  - git

runcmd:
  - systemctl enable docker
  - systemctl start docker

  - curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
  - echo 'export PATH=$HOME/yandex-cloud/bin:$PATH' > /etc/profile.d/yc_path.sh
  - chmod +x /etc/profile.d/yc_path.sh

  - git clone --depth 1 --branch "${repo_branch}" "${repo_url}" /opt/app
  - cd /opt/app/"${repo_path}"

  - yc config set service-account-key /etc/cloud/key.json
  - yc config set cloud-id "${cloud_id}"
  - yc config set folder-id "${folder_id}"
  - yc config set compute-default-zone "${zone}"

  - git clone --depth 1 --branch "${repo_branch}" "${repo_url}" /opt/app
  - cd /opt/app/"${repo_path}"

final_message: "App is up and running!"
