#cloud-config
users:
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    ssh_authorized_keys:
      - "${ssh_key}"
package_update: true
packages:
  - docker.io
  - docker-compose-plugin

runcmd:
  - systemctl enable docker
  - systemctl start docker
