name: myapp
services:
  web:
    image: cr.yandex/${REGISTRY_ID}/my-app:${VERSION_TAG}
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.5
    ports:
      - 8091:8090
    environment:
      DB_HOST: ${DB_HOST}           
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_DATABASE}
      DB_TABLE: ${DB_TABLE}

