name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Yandex CLI
        uses: yandex-cloud/setup-yc@v1
        with:
          version: latest
          service-account-key: ${{ secrets.YC_SA_KEY_JSON }}
          cloud-id: ${{ secrets.YC_CLOUD_ID }}
          folder-id: ${{ secrets.YC_FOLDER_ID }}
          compute-default-zone: ${{ secrets.YC_ZONE }}
          registry-id: ${{ secrets.YC_REGISTRY_ID }}

      - name: Log in to Container Registry
        run: yc container registry login

      - name: Build Docker image
        run: |
          IMAGE=cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_REGISTRY_ID }}/my-app:${{ github.sha }}
          docker build -t $IMAGE ./app
          echo "Image tagged as $IMAGE"

      - name: Push Docker image
        run: |
          docker push $IMAGE
