name: Docker Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore SA key from Base64
        shell: bash
        run: |
          printf '%s' "${{ secrets.YC_SA_KEY_BS64 }}" | base64 -d > key.json
          echo "YC_SERVICE_ACCOUNT_KEY_FILE=$(pwd)/key.json" >> $GITHUB_ENV

      - name: Debug key.json
        shell: bash
        run: |
          echo "File size: $(stat -c%s key.json) bytes"
          head -n5 key.json
          jq . key.json

      - name: Install Yandex Cloud CLI
        shell: bash
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          # подхватит PATH для следующих шагов
          echo "PATH=$HOME/yandex-cloud/bin:$PATH" >> $GITHUB_ENV

      - name: Verify yc
        run: |
          which yc
          yc --version

      - name: Configure Yandex CLI
        run: |
          yc config set service-account-key key.json
          yc config set cloud-id ${{ secrets.YC_CLOUD_ID }}
          yc config set folder-id ${{ secrets.YC_FOLDER_ID }}
          yc config set compute-default-zone ${{ secrets.YC_ZONE }}

      - name: Log in to Container Registry
        run: yc container registry login

      - name: Build Docker image
        run: |
          IMAGE=cr.yandex/${{ secrets.YC_CLOUD_ID }}/${{ secrets.YC_REGISTRY_ID }}/my-app:${{ github.sha }}
          docker build -t $IMAGE ./app
          echo "Image tagged as $IMAGE"

      - name: Push Docker image
        run: |
          docker push $IMAGE
